### ISSUE TITLE
 maximize* commands don't work for Emacs

### ISSUE THREAD

**Issue by davidhedlund** [dsalt/devilspie2#11]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 for the bug

**Comment by davidhedlund** [comment]
https://github.com/gitGNU/gnu_devilspie2/issues/1

**Comment by dsalt** [comment]
Just had another poke at this… *looks like* emacs is doing things to the window shortly after opening it, and that's conflicting with what devilspie2 is told to do.

Waiting for a short time seems to be enough to work around this.

```lua
if get_class_instance_name() == "emacs" then
  os.execute("sleep 0.5") -- ← 💤
  maximize()
  set_window_workspace(2)
end
```

**Comment by davidhedlund** [comment]
> Just had another poke at this… _looks like_ emacs is doing things to the window shortly after opening it, and that's conflicting with what devilspie2 is told to do.
> 
> Waiting for a short time seems to be enough to work around this.
> 
> ```lua
> if get_class_instance_name() == "emacs" then
>   os.execute("sleep 0.5") -- ← 💤
>   maximize()
>   set_window_workspace(2)
> end
> ```

Impressive, even 0.1 works fine on my computer:
```
if get_class_instance_name() == "emacs" then
  os.execute("sleep 0.1")
  maximize()
end
```

I'm very happy with your  help, big thanks!

So this is not a devilspie2 bug, I guess we should close it now, right?

**Comment by davidhedlund** [comment]
Please also read https://www.emacswiki.org/emacs/FullScreen#h5o-11

The preferred method for maximizing Emacs involves using an early-init.el file, which allows for quicker maximization compared to configuring it in init.el. However, many Emacs users prefer to keep all their configuration in init.el. In such cases, devilspie2 can be a useful alternative for achieving quick maximization without modifying the Emacs startup process.

What I just said here can also be added to the comments in your example script.

**Comment by davidhedlund** [comment]
I just updated my comment

**Comment by dsalt** [comment]
Questions, in order:

* Essentially, yes, though savannah is used for releases and the repository there is maintained. (I know that devilspie2 source in Debian has a watch file which points there, but it needs maintaining.)
* Well. It's more or less suitably tagged now, I think.
* This one and the one on savannah are handled. Up to you for the other one.

**Comment by davidhedlund** [comment]
> Questions, in order:
> 
>     * Essentially, yes, though savannah is used for releases and the repository there is maintained. (I know that devilspie2 source in Debian has a watch file which points there, but it needs maintaining.)
> 
>     * Well. It's more or less suitably tagged now, I think.
> 
>     * This one and the one on savannah are handled. Up to you for the other one.

Thank you!

And what do you think about the "Suggestion: Document the example" section in the comment above?

**Comment by davidhedlund** [comment]
Do you think that https://savannah.nongnu.org/bugs/?62848 can be solved by utilizing `sleep` too?

**Comment by dsalt** [comment]
Want to write something yourself? Fine if not, but either way it should be handled as a separate issue (or PR); and I do agree that it should be done.

As for savannah bug 62848, I should have a(nother) look at it before commenting.

**Comment by dsalt** [comment]
See #27.

The “log out and log back in” in the devilspie2 section in https://www.emacswiki.org/emacs/FullScreen is unnecessary if devilspie2 is already running; also, 0.45 provides a desktop file.

**Comment by davidhedlund** [comment]
> See #27.
> 
> The “log out and log back in” in the devilspie2 section in https://www.emacswiki.org/emacs/FullScreen should be unnecessary if devilspie2 is already running

I added "Log out and then log back into your desktop environment and start emacs, to make sure that devilspie2 autostarts and maximizes emacs."

> also, 0.45 provides a desktop file.

Sorry, what do you mean? I couldn't find anything about that at https://www.emacswiki.org/emacs/FullScreen#h5o-45

**Comment by davidhedlund** [comment]
> Want to write something yourself? Fine if not, but either way it should be handled as a separate issue (or PR); and I do agree that it should be done.

I didn't want to spoil the example documentation if you have personal preferences. But even if you have it, it's probably good if there are many different examples for the most popular programs, which emacs is part of.

I'm the right person to ask because i've actually spent maybe 1-2 full work weeks comparing different methods (devilspie2, and emacs LISP in different OS) how to maximize the emacs window _FAST_ without being visually distracting. I'll submit a PR for you.

> As for savannah bug 62848, it's an `xseticon` bug.

Thank you for having a look.

**Comment by davidhedlund** [comment]
Solved

**Comment by dsalt** [comment]
Re. the desktop file: the second part (`Autostart devilspie2`) of the script on that page creates one, and that's only useful for 0.44 and older.)

(If that “solved” is directed at #27, better to comment there.)

**Comment by davidhedlund** [comment]
> Re. the desktop file: the second part (`Autostart devilspie2`) of the script on that page creates one, and that's only useful for 0.44 and older.)
> 
> (If that “solved” is directed at #27, better to comment there.)

That's great! I added "Devilspie2 0.44 and earlier versions do not include a desktop file, requiring users to create one manually:" to https://www.emacswiki.org/emacs/FullScreen

**Comment by davidhedlund** [comment]
I just
* Closed https://github.com/gitGNU/gnu_devilspie2/issues/1
* Emailed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 that this bug report is invalid, the workaround, and the link to the PR of the documentation of the workaround.

You can close this issue when you want (seems like I cannot do that for some reason).

**Comment by davidhedlund** [comment]
I just
* Closed https://github.com/gitGNU/gnu_devilspie2/issues/1
* Emailed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 that this bug report is invalid, the workaround, and the link to the PR of the documentation of the workaround.

You can close this issue when you want (seems like I cannot do that for some reason).

**Comment by davidhedlund** [comment]
I just
* Closed https://github.com/gitGNU/gnu_devilspie2/issues/1
* Emailed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 that this bug report is invalid, the workaround, and the link to the PR of the documentation of the workaround.

You can close this issue when you want (seems like I cannot do that for some reason).

**Comment by davidhedlund** [comment]
I just
* Closed https://github.com/gitGNU/gnu_devilspie2/issues/1
* Emailed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 that this bug report is invalid, the workaround, and the link to the PR of the documentation of the workaround.

You can close this issue when you want (seems like I cannot do that for some reason).

**Comment by davidhedlund** [comment]
I just
* Closed https://github.com/gitGNU/gnu_devilspie2/issues/1
* Emailed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033471 that this bug report is invalid, the workaround, and the link to the PR of the documentation of the workaround.

You can close this issue when you want (seems like I cannot do that for some reason).
