### ISSUE TITLE
documentation: homepage, manual, man page, readme

### ISSUE THREAD

**Issue by CouldBeThis** [dsalt/devilspie2#19]
https://www.nongnu.org/devilspie2/ says:

> Also see the latest version of the complete [README](http://git.savannah.gnu.org/cgit/devilspie2.git/plain/README) and the [manual](https://www.nongnu.org/devilspie2/manual.php) (WIP).

Manual link is 404. Attempted to find via site search but unsuccessful. 

`man devilspie2` is quite brief and suggests 

> More details in /usr/share/doc/devilspie2/README.
> ...
> Script Commands
> See the README or the manual linked from the homepage for a detailed description of the commands recognized by the Lua script.

The README is pretty extensive. Is there in fact another document? If yes then is it possible to make it available somewhere? Website should be update to fix the link or remove the reference from website and `man` page.

In either case I suggest adding the URL of the homepage to the `man` page for clarity. It is found at the bottom of the README but a person may not notice it. 

Perhaps it would be worthwhile to put the README text directly into the `man` page since that is the standard location.

**Comment by dsalt** [comment]
I've done some clean-up of the project page, which includes removing or marking dead links.

I have no plans to move the content of README into any other document.
