### ISSUE TITLE
get_window_name() does not get updated

### ISSUE THREAD

**Issue by tsjk** [dsalt/devilspie2#22]
I wanted to automate the positioning if my IntelliJ IDEA windows under XFCE (as that doesn't seem to work out of the box for some reason). I stumbled upon a few problems though that are tied to the fact that there is a delay between window creation and the setting of a name.
When the application starts `get_window_name()` returns `" "`, and seems to remain that way. Here is a work-around:
```
-- Window rules for IntelliJ IDEA.
if ((get_class_group_name() == "jetbrains-idea") and (get_class_instance_name() == "jetbrains-idea") and (get_window_type() == "WINDOW_TYPE_NORMAL")) then
	if (get_window_property('WM_NAME') == " ") then
		n = get_window_property('WM_NAME')
		l = 8
		while ((l > 0) and (n == " ")) do
			os.execute("sleep .25")
			l = l - 1
			n = get_window_property('WM_NAME')
		end
	end
	if ((get_window_name() == " ") and (n ~= nil) and (n ~= " ")) then
		if (string.find(n, " – ") == 1) then
			-- Main window
			unmaximize()
			set_window_geometry(1920 + 2560 + 4, 360, 2560, 1440)
		else
			-- Extra code window
			unmaximize()
			set_window_geometry(1920 + 2560 + 2560 - 4, -1924, 1200 - 2, 1920 - 2)
		end
	end
end
```

I wonder - could use cases such as these be handled in a better way?

**Comment by mark-cooke** [comment]
@tsjk Recently, @dsalt kindly accepted my pull requests, one of which will handle your use case (I created it to handle the same problem I was having with firefox).

See https://github.com/dsalt/devilspie2/blob/760df8ce0db8f51c75acbb27ab0e420174cb8352/README#L50 for instructions about how to set it up.

**Comment by dsalt** [comment]
@tsjk, if this is now fixed for you, you should close this or let me know that it should be closed.

**Comment by tsjk** [comment]
Yes, this does help a lot. Although I had to write quite an advanced lua program to handle jetbrains window naming. Basically, I wanted to place coding windows on different screens depending on what project they belong to. =)
Without these new changes it'd be even more difficult or even impossible. Thanks.
