### ISSUE TITLE
Makefile race condition

### ISSUE THREAD

**Issue by ionenwks** [dsalt/devilspie2#8]
It's very unlikely, but got an automated report at https://bugs.gentoo.org/881473 where `obj/` dir hadn't been created yet given using `$(BIN)/$(NAME): $(OBJ) $(OBJECTS)` rather than `$(OBJECTS): $(OBJ)` or so, and order isn't guaranteed.
```
Assembler messages:
Fatal error: can't create obj/devilspie2.o: No such file or directory
make: *** [Makefile:101: obj/devilspie2.o] Error 1 shuffle=2250841411
```

May or may not be able to reproduce if use GNU make-4.4 and its new shuffle option with the same seed:
```
GNUMAKEFLAGS="--shuffle=2250841411" make
```

**Comment by dsalt** [comment]
I'm still unable to test my fix for this as I don't yet have a new enough version of GNU make.

**Comment by ionenwks** [comment]
Can't reproduce anymore with the fix.

Guess I'll go ahead and close this, thanks.

**Comment by ionenwks** [comment]
> Guess I'll go ahead and close this, thanks.

Well, maybe I closed a bit prematurely,  I see it's not on master yet. But imagine it won't be long anyway.
